### ISSUE TITLE
Set Default Author

### ISSUE THREAD

**Issue by harmonherring** [harmonherring/CTF-UI#14]
On Challenge creation modal, author isn't being set by default. Set it to the current user when the modal is loaded. Otherwise submissions don't work :)

**Comment by stefanuslim** [comment]
Hi, can I work on this?

**Comment by harmonherring** [comment]
Hi @stefanuslim! Thanks for the offer, but I just resolved this before seeing your comment, sorry about that. Feel free to take a stab at any other issues here or on the API (https://github.com/harmonherring/CTF-API). I'll be sure to put up some new ones if you're looking for something to do
